### ISSUE TITLE
performance problem on large grid

### ISSUE THREAD

**Issue by GCat** [gjuchault/pathfindingjs#1]
seems to be a big lag on a large open grid
## for example:

var Pathfinding = require('.');

var grid = [];

var height = 2000;
var width  = 2000;

var startPos = [10, 10];
var endPos   = [1080, 1080];

for (var i = 0; i < height; ++i) {
    grid[i] = [];
    for (var j = 0; j < width; ++j) {
        grid[i][j] = 0;
    }
}

var finder = new Pathfinding(grid);
finder
    .setFrom(startPos[0], startPos[1])
    .setTo(endPos[0], endPos[1]);

console.log('From', '(' + startPos[0] + ',' + startPos[1] + ')');
console.log('To',  '(' + endPos[0] + ',' + endPos[1] + ')');

var d1 = (new Date()).getTime();
var path = finder.find();
var d2 = (new Date()).getTime() - d1;

if (path !== false) {
    console.log('Found in ' + (d2 / 1000) + 's');
} else {
    console.log('Not found in ' + (d2 / 1000) + 's')
}

---

looks like a bug, other pathfinders in js can find it instantly,
and this is c++ so it should be much faster
instead it takes 25-30 seconds

**Comment by gjuchault** [comment]
If you're any interested on helping me with this; here is a performance call of the native C++ executable (`npm install && ./native.sh`) with vallgrind.
http://www.filedropper.com/callgrindout

I made a 500*500 map, searching from 0;0 to 499;499. There is a segfault when I try from 0;0 to 500;500

Here is a screenshot of KCacheGrind watching the file. 
![image](https://cloud.githubusercontent.com/assets/678848/11563711/a3ee3c4e-99d5-11e5-8feb-e3d412167936.png)

I don't really know how to make this faster, but there is obviously a problem

**Comment by gjuchault** [comment]
In fact, I didn't need to call `make_heap` as I was using a `priority_queue`. It would have been a good idea if I was using a `List`/`Set`

**Comment by gjuchault** [comment]
So this is basically closed :) Thanks ;)
